### ISSUE TITLE
shallowEquals throws exception if mapper returns non-object value

### ISSUE THREAD

**Issue by farwayer** [xuoe/redux-observers#3]
imho it's more correct to make simple equal check (`===`) as default behaviour and leave more complex situations to custom equal functions.

**Comment by xuoe** [comment]
I couldn't get it to throw, but I realized primitive values weren't checked properly. Even though I see your point regarding a simpler equality check, I'd rather have the behavior offered by `shallowEquals` on by default.

Thanks, closing for now.
