### ISSUE TITLE
`_.isPrimitive(null)` returns false? 

### ISSUE THREAD

**Issue by Javran** [xuoe/redux-observers#4]
I used `null` when the slice of interest is not available, and `shallowEquals` throws expecting observed value to be objects. By digging a bit I found `_.isPrimitive(null)` is returning `false` despite it being a js primitive. for now as a workaround I wrapped the value in an object. is this the intended behavior?

**Comment by xuoe** [comment]
Yes, you are correct: given the function name and the fact that `null` is a primitive, `isPrimitive(null)` should return `true`. (Symbols are not accounted for either.)

> `shallowEquals` throws expecting observed value to be objects

I'm not able to get `shallowEquals` to throw. Moreover, [there are tests that make use of primitive values](https://github.com/xuoe/redux-observers/blob/dea9db42e321078db3d80e826ee78704443994dc/test/index.js#L24-L36), all of which are passing (albeit none of them test against `null` values yet). Before I push a fix, I'd like to see a code sample that showcases `shallowEquals` throwing, if you don't mind.

Thanks for filing the issue.

**Comment by Javran** [comment]
Thanks for the response! Fortunately there's an easy way to reproduce the throw, just add `[false, {}, null]` after [this line](https://github.com/xuoe/redux-observers/blob/dea9db42e321078db3d80e826ee78704443994dc/test/index.js#L35) and run the tests.

**Comment by xuoe** [comment]
Yep, that was it, thanks! I published a [patch](https://github.com/xuoe/redux-observers/commit/02d6e3ee4c8bf7ec3bf35cfcf0a950d751202e37) to npm. If you think the issue has been addressed, feel free to close it.

**Comment by Javran** [comment]
Thanks for the fix, I can confirm it's now working as expected.
